### ISSUE TITLE
Change language in other ViewControllers

### ISSUE THREAD

**Issue by Tindi** [marmelroy/Localize-Swift#101]
Hi @marmelroy! Thanks for this awesome library. I'm able to change the language on my Language ViewController and see the change. When I open my other ViewControllers the language hasn't changed on my set strings. When I quit the app and reopen they have changed though. How can I have other ViewControllers changed as well?

**Comment by VishnuMU** [comment]
Once the app loads a view and keeps in cache viewDidLoad is not called. That is why it is not refreshing in your view.

This is not an issue. You are not handling the view cycle properly especially for this library.

Call your set strings function on `viewWillAppear().`

**Comment by Tindi** [comment]
Hi @VishnuMU I managed to do it way back when. I loaded them in `viewWillAppear()` thanks though.
