### ISSUE TITLE
How to check the device current language using Localize-Swift?

### ISSUE THREAD

**Issue by hemangshah** [marmelroy/Localize-Swift#113]
Is there a way to find out the device current language? I mean the language which is set in Settings by the user. So when our app would get installed before setting any language changes, if we can check for the device language?

**Comment by Marcello168** [comment]
I was meet this question  too ? do you solve it?

**Comment by apradanos** [comment]
This works for me: 

`Localize.currentLanguage()`

**Comment by bhaveshlsamcom** [comment]
Localize.currentLanguage() No, it's giving app language not device language, any one has any idea how to get device language? Device -> Setting -> General -> Language

**Comment by bhaveshlsamcom** [comment]
@hemangshah please let me know if you got the solution.
