### ISSUE TITLE
Typo: Localize.resetCurrentLanguageToDefault()

### ISSUE THREAD

**Issue by rosevinod** [marmelroy/Localize-Swift#12]
please change the typo mistake:

@IBAction func doResetLanguage(sender: AnyObject) {
        Localize.resetCurrentLanguageToDefault() >>>>> to >>> resetCurrentLanaguageToDefault()
    }

**Comment by cyrus86** [comment]
'language' is correct...

**Comment by rosevinod** [comment]
I know that "language" word is correct but method name you have given having typo..... search for "resetCurrentLanaguageToDefault" in project ...

**Comment by marmelroy** [comment]
@cyrus86 is right. Basically the solution is to package a new release together but I want to make a small change first. Fix coming soon...

**Comment by marmelroy** [comment]
New release pushed. Please update and the issue should be solved. Closing for now.
