### ISSUE TITLE
I wonder why my app not changing language

### ISSUE THREAD

**Issue by SamboVisal** [marmelroy/Localize-Swift#122]
I am using CocoaPods to install this library. 
And then i started to add language that i want to translate for my app
![screen shot 2561-12-04 at 7 15 53 pm](https://user-images.githubusercontent.com/29918870/49441455-179eca80-f7f9-11e8-942c-d8a57bb3f9be.png)

And then i created string file in order to translate language
![screen shot 2561-12-04 at 7 18 21 pm](https://user-images.githubusercontent.com/29918870/49441548-62b8dd80-f7f9-11e8-8e9f-357291850f19.png)

And this is my main viewController
![screen shot 2561-12-04 at 7 20 11 pm](https://user-images.githubusercontent.com/29918870/49441608-a4498880-f7f9-11e8-8423-53d2aef1cbf1.png)

When i run the app and still show me Hello world text.

Thank for help me out.

**Comment by uyphanha** [comment]
**km-KH** is the language code of Khmer Language.

**Comment by SamboVisal** [comment]
@uyphanha orkun bong for helping me out

**Comment by uyphanha** [comment]
@SamboVisal you're welcome, bro.
