### ISSUE TITLE
Project broke on new Xcode 10.2

### ISSUE THREAD

**Issue by snowtema** [marmelroy/Localize-Swift#131]
**Describe the bug**
After upgrading on the new version of Xcode 10.2, the project doesn't compile with an error:
```
Error: module map file '/Users/_REDACTED_/Pods/Headers/Public/Localize_Swift/Localize-Swift.modulemap' not found
Error: missing required module 'SwiftShims'
```

If I'll delete **pod** and comment **associated code** then the project will successfully be compiled.

**To Reproduce**
1. Upgrade to Xcode 10.2 
2. Try to build project
3. See error

**Expected behavior**
Successfully build projects

**Screenshots**

**Environment (please complete the following information):**
 - Device: any
 - OS: OS X 10.14.4
 - Xcode Version 10.2
 - Swift Version 5
 - pod version 2.0.0

**Installation Type**
 - Cocoapods

**Comment by fassko** [comment]
Support for Swift 5 has been released.
