### ISSUE TITLE
New release for Swift 5 support?

### ISSUE THREAD

**Issue by getaaron** [marmelroy/Localize-Swift#134]
I see Swift 5 support was added in https://github.com/marmelroy/Localize-Swift/commit/0af1491dc1f8f029fb3ca88a67a89b2324ca0019. Would it be possible to cut a new release?

**Comment by NickGaens** [comment]
Also, please consider pushing a new release to the Cocoapods repo.

**Comment by fassko** [comment]
In coming weeks I will take care of this.

**Comment by dawigr** [comment]
Could you guys cut a cocoa pod release please with Swift 5. It's really annoying to see only 1 warning in the whole project from you.

**Comment by fassko** [comment]
New version with Swift 5 support has been released.
