### ISSUE TITLE
Swift Package Manager Xcode 11.1 Error Dependency

### ISSUE THREAD

**Issue by episquare** [marmelroy/Localize-Swift#141]
Got this error 'The package dependency graph can not be resolve'

**Comment by fassko** [comment]
Yep we have issue for that https://github.com/marmelroy/Localize-Swift/issues/140

If you can help with PR would help to speed it up. :)

**Comment by gcharita** [comment]
@episquare it seems that the latest commit in master branch tackle that issue.

Just use specific branch when you add the dependency in Xcode:
![Screenshot 2019-10-31 at 12 04 48 PM](https://user-images.githubusercontent.com/16266885/67937945-2f342e00-fbd7-11e9-9782-0c5b756dfc28.png)

**Comment by fassko** [comment]
Version 3.1.0 will fix this issue, thanks.
