### ISSUE TITLE
Support ignored directories with genstrings.py

### ISSUE THREAD

**Issue by nuudles** [marmelroy/Localize-Swift#15]
Running `genstrings.py` currently searches all directories, including Examples in the Carthage Checkouts folder. For instance, I get this output:

```
/*
 * ./Carthage/Checkouts/Localize-Swift/examples/LanguageSwitch/Sample/ViewController.swift
 */

"Hello world" = "Hello world";

"Change" = "Change";

"Reset" = "Reset";
```

It would be helpful to have an `--ignore` option to ignore certain directories.

**Comment by marmelroy** [comment]
Sorry for the delay @nuudles. Spent some time thinking about this and I actually want to rewrite the genstrings script in Swift. I'll make sure to add an ignore option.

**Comment by emilpedersen** [comment]
+1

**Comment by marmelroy** [comment]
I just added a new genstrings script written entirely in Swift that supports ignored directories and ignored filenames. You can edit the file to specify your own https://github.com/marmelroy/Localize-Swift/commit/3ec6c27bd3029151bee96aca459966de68bbbf52
