### ISSUE TITLE
iOS 7 support

### ISSUE THREAD

**Issue by emrsn-SebastianVancea** [marmelroy/Localize-Swift#18]
When trying to install via cocoapods, if your project has a deployment target earlier than 8.0 (the one the pod is built with), you cannot install the pod. 
According to the docs, Swift 2.0 is backwards compatible with iOS 7.0.

Appreciate the work!

**Comment by marmelroy** [comment]
Hi @emrsn-SebastianVancea, I'm afraid iOS7 support is not possible. Embedded Swift dylibs/frameworks only run on iOS 8 or later. 

If you want to use Localise-Swift in an iOS7 app you can do so manually by adding https://github.com/marmelroy/Localize-Swift/blob/master/Sources/Localize.swift to your project.
