### ISSUE TITLE
Wrong .lproj path if base localization is en

### ISSUE THREAD

**Issue by gbmksquare** [marmelroy/Localize-Swift#20]
Base localization is English, added a new localization in Korean.

`NSBundle.mainBundle().localizations` returns ["Base", "ko", "en"]

`Localize.currentLanguage()` returns "en" instead of "Base" and since `en.lproj` doesn't exist localization string for English is not showing.

```Swift
func localized() -> String {
    if let path = NSBundle.mainBundle().pathForResource(Localize.currentLanguage(), ofType: "lproj"), bundle = NSBundle(path: path) {
        return bundle.localizedStringForKey(self, value: nil, table: nil)
    }
    return self
}
```

**Comment by marmelroy** [comment]
This was actually solved by https://github.com/ivanbruel/Localize-Swift/commit/aec3737155f377946e64ba84a73b8afce36c96c8 but was somehow lost in subsequent changes. Bringing it back.
