### ISSUE TITLE
Can't run on i386

### ISSUE THREAD

**Issue by fcouceiro** [marmelroy/Localize-Swift#21]
If I try to run my app on iPhone 5 or iPhone 4s (using the simulator), xcode doesn't compiles and gives this error
`Localize_Swift, file was built for x86_64 which is not the architecture being linked (i386)`

I've imported the library using Carthage.

Anything I can do?

**Comment by marmelroy** [comment]
Solved by https://github.com/marmelroy/Localize-Swift/commit/cac9f41c3fd0b518776b8d5faabe0279449c347d.
