### ISSUE TITLE
is there a way to add comments when using localized()  method?

### ISSUE THREAD

**Issue by senseluo** [marmelroy/Localize-Swift#23]
hi @marmelroy ,

Thank you for your awesome work, I am currently using it in my own project.
Is there any possible add some comments when using localized() method.
I think this could be an important option for those with similar text but different meaning on context.

Thanks!

**Comment by marmelroy** [comment]
Sorry for the long delay in replying to this one @senseluo and thanks for the suggestion. There isn't a way to add comments when using localized() currently but it's definitely something that should be added in the future. 
 
I am planning on rewriting the genstrings python script in Swift (already started( but finding the time to finish it is currently difficult. As soon as it is finished, I will add comment support in localised().
