### ISSUE TITLE
string like "%@yo"  will not be recognized if duplicate items occurred

### ISSUE THREAD

**Issue by senseluo** [marmelroy/Localize-Swift#27]
I am gonna do some translation like "25yo" which the "25" passed as a variable outside.
Currently I found the python script will not sort it out if more than one times occurred in my code.

Seems it is a bug.

Thanks!

**Comment by marmelroy** [comment]
Fixed by https://github.com/marmelroy/Localize-Swift/commit/b7e6835397fdd27a9a445ef390a495b16fc54ce4
