### ISSUE TITLE
Refreshing the storyboard on language change

### ISSUE THREAD

**Issue by bart-kneepkens** [marmelroy/Localize-Swift#29]
Is there any way to reload a storyboard when you change the language? Currently when I change the language the Strings with .localized() work but the storyboard does not change at all.

**Comment by marmelroy** [comment]
As far as I know this is not possible. 

It is generally better to only set placeholder strings in storyboards and localizable strings in code.

**Comment by ashchan** [comment]
To use storyboard without manually mapping UI elements, consider this lib (https://github.com/maximbilan/ios_language_manager). When changing language, call `NSBundle.setLanguage(lang)` and reload current view controller form storyboard manually.
