### ISSUE TITLE
localizedFormat not picked up by genstrings.py

### ISSUE THREAD

**Issue by SASDOE** [marmelroy/Localize-Swift#32]
Given this
```swift
"\nAnd %d more!".localizedFormat(aNumber)
```
genstrings.py doesn't generate any output for this string. 

The reason behind this is because the regex matches localizedWithFormat, a non existing method.

**Comment by marmelroy** [comment]
Fixed by https://github.com/marmelroy/Localize-Swift/commit/46d13c461c0f21be0e7437112f5d62080778a6d2

**Comment by marmelroy** [comment]
Thanks for reporting, just a typo.
