### ISSUE TITLE
Local date

### ISSUE THREAD

**Issue by Jkurbs** [marmelroy/Localize-Swift#34]
` var dateFormatter = NSDateFormatter()
    override func viewDidLoad() {
        super.viewDidLoad()
        dateFormatter.dateStyle = .MediumStyle
        let timeString = "\(dateFormatter.stringFromDate(NSDate()))"
        dateLbl.text = timeString
        print(timeString)
    }
`

Hi Roy, how can I Localized a date? Is it possible? 

Thank you very much!

**Comment by marmelroy** [comment]
Hey @Jkurbs,

You can localise a date! Just add
```dateFormatter.locale = NSLocale(localeIdentifier: Localize.currentLanguage())```
before stringFromDate.

**Comment by Jkurbs** [comment]
Thank you sooo much @marmelroy !
