### ISSUE TITLE
Include Localizable.strings content in xCode's "export for localization"

### ISSUE THREAD

**Issue by ribasal1** [marmelroy/Localize-Swift#35]
Hello,
is there a way to include the content of Localizable.strings in xCode's exported for translation .xliff files? 
At the moment, it doesn't work because xcode searches for NSLocalizedString in code, not for actual content in Localizable.strings
If you have any thought, it will be much appreciated. 
Thanks

**Comment by marmelroy** [comment]
Hi @ribasal1,

Sorry for the long delay. I'm afraid this is not currently possible (as far as I know).

Sorry again,
Roy
