### ISSUE TITLE
Remove  Base language

### ISSUE THREAD

**Issue by Jkurbs** [marmelroy/Localize-Swift#36]
Hi Roy :) 
Right now my alertController look like this:
<img width="292" alt="screen shot 2016-05-25 at 10 45 28 pm" src="https://cloud.githubusercontent.com/assets/10508898/15729614/d24cca0a-2833-11e6-9798-dca97f2c09a8.png">

How can i remove the base language. When i 
>   print(self.availableLanguages)

. I get this result ["Base", "en", "fr"]. But I just want ["en, "fr"].

Thank you very much!

**Comment by marmelroy** [comment]
Thanks @Jkurbs. 

I just added the ability to exclude Base (will be packaged in the next release). 

https://github.com/marmelroy/Localize-Swift/commit/b3d20dafd2184d86a768c736a6504bcaa6799dbe

Just:
```
Localize.availableLanguages(true)
```
(it will get a nicer syntax in Swift 3)
