### ISSUE TITLE
Please support osx

### ISSUE THREAD

**Issue by qiuyuzhou** [marmelroy/Localize-Swift#37]
The platform of the target `ShadowsocksX-NG` (OS X 10.10) is not compatible with `Localize-Swift (1.1.2)`, which does not support `osx`.

**Comment by marmelroy** [comment]
Thanks @qiuyuzhou. I'm working on this for the next Localise update...

**Comment by marmelroy** [comment]
Pushed (will be packaged in the next release) https://github.com/marmelroy/Localize-Swift/commit/20e27738f9fb77376dc108a5cb13506ccf910a3a
