### ISSUE TITLE
.localized() always returns English version

### ISSUE THREAD

**Issue by tolik85** [marmelroy/Localize-Swift#38]
Hello,

No matter what I am doing, after settings the language to any different language than "en", I always get translations from Localizable.strings of my en.lproj.

I am using: 
Localize.setCurrentLanguage("fr-FR") 

and then after LCLLanguageChangeNotification notification, I call:
backButton.setTitle("Back".localized(), forState: .Normal)

The result is always the string "BACK".

Am I doing something wrong?

Thanks!

**Comment by marmelroy** [comment]
Hello @tolik85! 

I'm afraid so... "fr-FR" is a valid locale code but not a valid language code (it basically causes localize to look for an "fr-FR.Iproj"). 

You should write: 
```
Localize.setCurrentLanguage("fr")
```

To see the available language codes in your app, try 
```
Localize.availableLanguages()
```

Hope this helps.
Roy

**Comment by tolik85** [comment]
Sorry, but this does not help

**Comment by marmelroy** [comment]
can you paste

**Comment by marmelroy** [comment]
Okay... can you paste what you see on 
```
print(Localize.availableLanguages())
```

**Comment by tolik85** [comment]
The language is need is Hebrew:

["Base", "en", "he-IL", "he", "hi", "pa-IN"]

**Comment by marmelroy** [comment]
and doing 
```
Localize.setCurrentLanguage("he")
```
doesn't work?

If so that's very strange. I can have a quick look if you share your code (either here or via e-mail to marmelroy@gmail.com).

**Comment by mhtranbn** [comment]
me too this error! Please support @marmelroy

**Comment by danchokobo** [comment]
@mhtranbn @tolik85 did help you @marmelroy ? did you solve problem?
