### ISSUE TITLE
incremental update of Localizable.string

### ISSUE THREAD

**Issue by hashemp206** [marmelroy/Localize-Swift#44]
how can I use provided genstrings.py file to incremental update Localizable.string file?

**Comment by alibasta** [comment]
Thats also my question. :-) Any answers?

**Comment by marmelroy** [comment]
Hi @hashemp206 and @alibasta. 

Firstly, genstrings.py is dead and was replaced by a genstrings.swift file. 

The file will print out all of the localisable strings in your project but currently it doesn't automate diffing for incremental updates. Maybe that's something to consider for a future update.
