### ISSUE TITLE
Carthage build error in Xcode8 & Swift 3.0

### ISSUE THREAD

**Issue by dqj274** [marmelroy/Localize-Swift#48]
Hi, 
while i'm trying to compile the Localize-Swift using carthage.  i'm getting an Error.

The log file:
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

Environment: 
Xcode 8.0 Build version 8A218a
Swift 3.0
carthage version 0.18
Localize-Swift 

Cartfile 
github "marmelroy/Localize-Swift" "swift3.0"

**Comment by x-june** [comment]
same problem here with cocoa pods

**Comment by marmelroy** [comment]
Fixed with 1.6. Thanks for the patience @x-june and @dqj274.
