### ISSUE TITLE
xCode8 with Swift2.3

### ISSUE THREAD

**Issue by kristijanexads** [marmelroy/Localize-Swift#49]
Hi, is there Carthage support for xCode8+Swift2.3? At the moment I can't move straight to Swift3 because some other frameworks that I'm using are not updated.

**Comment by marmelroy** [comment]
Hi @kristijanexads ! 

I'm afraid that Localize only maintain a Swift 3.0 branch (following 3.0's official release). 

However, the previous release, 1.5, should run well with Swift 2.3 and Xcode 8 (some minor modifications might be needed but it shouldn't be too difficult). 

I think you can use the tag with Carthage. 

Hope this helps,
Roy

**Comment by kristijanexads** [comment]
Hi again @marmelroy 
It works now, here is the answer in case someone else needs it:
add this to Cartfile
<code>github "marmelroy/Localize-Swift" == 1.5</code>

and run:
<code>carthage build --platform iOS --toolchain com.apple.dt.toolchain.Swift_2_3 Localize-Swift</code>
