### ISSUE TITLE
Swift 2.0 Compatibility

### ISSUE THREAD

**Issue by howie-misfit** [marmelroy/Localize-Swift#6]
Hi,

Do you want to fix the warnings and errors with Swift 2.0 Xcode 7?

**Comment by marmelroy** [comment]
Sure. Thanks. Will do it tonight.

**Comment by marmelroy** [comment]
Fixed as part of a big update.

Also created a more Swift 2.0 inspired localization syntax 

``` 
textLabel.text = "Hello World".Localized()
```

**Comment by howie-misfit** [comment]
Cool.
