### ISSUE TITLE
Not working localization!

### ISSUE THREAD

**Issue by danchokobo** [marmelroy/Localize-Swift#65]
Hello!
I installed by cocoapods,
this is my code: 
```
 let langs = ["kk", "ru", "en"]
                if i > 0 && i < langs.count {
                    Localize.setCurrentLanguage(langs[i])
                    let langStr = Locale.current.languageCode
                    print("yazik: \(langStr)")


```

and it is prints: only English, whenever I set other language:(

**Comment by denirorobert** [comment]
Locale.current.languageCode returns the language code of the device. 
Localize.setCurrentLanguage(langs[i]) will not language code of the device.
