### ISSUE TITLE
Suggestion: Change the Localized() method name to localized() to match style best practices

### ISSUE THREAD

**Issue by nuudles** [marmelroy/Localize-Swift#7]
The library looks great! I believe that the `Localized()` method should be renamed to `localized()` though as Swift conventions dictate that method names start with a lowercase letter. For instance, check out this style guide: https://github.com/raywenderlich/swift-style-guide

> Use descriptive names with camel case for classes, methods, variables, etc. Class names should be capitalized, while method names and variables should start with a lower case letter.

**Comment by alikaragoz** [comment]
:+1:

**Comment by marmelroy** [comment]
Thanks @nuudles and @alikaragoz. Great suggestion. I'll make a breaking change in a new release that will fix this tonight.

**Comment by marmelroy** [comment]
Fixed.
