### ISSUE TITLE
Can not get localized string in swift files using genstrings.py

### ISSUE THREAD

**Issue by howie-misfit** [marmelroy/Localize-Swift#8]
I am using Swift 2 and have already import Localize to do i18n.

Everything works well, but i can not use genstrings.py to get the localized source string in swift files:

In swift file( test.swift):
label.text = "Name".localized()

after i run genstrings.py, nothing in the terminal, i suppose it could be like this:

/*
 * ./test.swfit
 */

"Name" = "Name";

I am not familiar with RE and Python, after i tried many times, it still can not work as i hope.

can you help to fix it?

**Comment by marmelroy** [comment]
Thanks for finding this issue. Looks like there was a bug in the regular expression I was using. Fixed in the latest commit. Will do a cocoapods release too.

**Comment by howie-misfit** [comment]
👍
