### ISSUE TITLE
Pluralization with Localize-Swift

### ISSUE THREAD

**Issue by MikhailKupriyanov** [marmelroy/Localize-Swift#87]
How use pluralization with Localize-Swift?

**Comment by robfeldmann** [comment]
I was just wondering the same thing, noticed your question, and thought I'd share with you my findings.

First, you'll need to read up on how regular pluralized localization works in Cocoa if you weren't using Localize-Swift. This was an excellent resource, which you should read all the way to the end: [http://crunchybagel.com/localizing-plurals-in-ios-development/](http://crunchybagel.com/localizing-plurals-in-ios-development/)

Basically, in addition to the `Localizable.strings` file you're used to, you need a `Localizable.stringsdict` file as well.

Then, for example, you'd call these `String` functions like so, which uses the `.stringsdict` file:

```
let format = NSLocalizedString("number_of_days", comment: "")
let message = String.localizedStringWithFormat(format, numDays)
```

So, in looking at Localize-Swift's source, we see that its `localizedPlural(_:)` method calls `String.localizedStringWithFormat`. 💥

```
func localizedPlural(_ argument: CVarArg) -> String {
    return NSString.localizedStringWithFormat(localized() as NSString, argument) as String
 }
```

I've never done any of this (yet) but this sure seems like how it all works. Good luck!

**Comment by MikhailKupriyanov** [comment]
Thanks Rob!

**Comment by rromanchuk** [comment]
Hmm, something is not right. 

```swift
let format = NSLocalizedString("%d players", comment: "")
let pluralMessage = String.localizedStringWithFormat(format, activePlayersCount)
// returns correct "1 player" 

let pluralMesasage2 =  "%d players".localizedPlural(activePlayersCount)
// returns incorrect "1 players" 
```
`NSLocalizedString` returns  "%#@num_players@" so `localizedStringWithFormat` works correctly. 

Localizable.stringsdict
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>%d players</key>
	<dict>
		<key>NSStringLocalizedFormatKey</key>
		<string>%#@num_players@</string>
		<key>num_players</key>
		<dict>
			<key>NSStringFormatSpecTypeKey</key>
			<string>NSStringPluralRuleType</string>
			<key>NSStringFormatValueTypeKey</key>
			<string>d</string>
			<key>zero</key>
			<string>Join now</string>
			<key>one</key>
			<string>%d player</string>
			<key>two</key>
			<string>%d players</string>
			<key>few</key>
			<string>%d players</string>
			<key>many</key>
			<string>%d players</string>
			<key>other</key>
			<string>%d players</string>
		</dict>
	</dict>
</dict>
</plist>
```
Localizable.strings
```
"%d players" = "%d players";
```

**Comment by mpkupriyanov** [comment]
Hi Ryan.

Different languages have their own rules of plural.
http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html

in your case:

Localizable.stringsdict

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>%d players</key>
	<dict>
		<key>NSStringLocalizedFormatKey</key>
		<string>%#@num_players@</string>
		<key>num_players</key>
		<dict>
			<key>NSStringFormatSpecTypeKey</key>
			<string>NSStringPluralRuleType</string>
			<key>NSStringFormatValueTypeKey</key>
			<string>d</string>
			<key>one</key>
			<string>%d player</string>
			<key>other</key>
			<string>%d players</string>
		</dict>
	</dict>
</dict>
</plist>
```


for zero value:
`let pluralMesasage2 = activePlayersCount == 0 ? "Join now" : "%d players".localizedPlural(activePlayersCount)`

**Comment by rromanchuk** [comment]
I'm not sure what you're trying to say, i'm aware of linguistic grammar of plurals, and you do not have to branch on zero case, it's included in the `stringsdict` file

My point is, it's working fine without using this library (sanity test, my stringsdict and strings file is properly setup)

```swift
let format = NSLocalizedString("%d players", comment: "")
let pluralMessage = String.localizedStringWithFormat(format, 0)
// returns correct "Join now" 
```

**Comment by rromanchuk** [comment]
Probably just user error, I'll try again, i was tired last night. спасибо bольшое, мне нужен кофе)))

**Comment by cyg02032015** [comment]
![image](https://user-images.githubusercontent.com/11013460/123392046-33446900-d5cf-11eb-886e-528944718640.png)
When i debugging stringdict It's always return "1 labels created"
Dont't forget the stringdict need select Localize then it work!!!
![image](https://user-images.githubusercontent.com/11013460/123392332-85858a00-d5cf-11eb-9c40-b615ec043a09.png)
![image](https://user-images.githubusercontent.com/11013460/123392367-8dddc500-d5cf-11eb-92d6-97c8495a8328.png)
