### ISSUE TITLE
Localize with Xcode 9

### ISSUE THREAD

**Issue by Nauman7222** [marmelroy/Localize-Swift#91]
I am try to localise in Arabic and unable to do that. setup my project as per example project, after language selection notification is calling but UI remained same. please let me know where i am doing wrong or missing something. i attached my project.
[SecondArabic.zip](https://github.com/marmelroy/Localize-Swift/files/1352137/SecondArabic.zip)

**Comment by MikhailKupriyanov** [comment]
Hello. 
For button: 
button.setTitle("Change".localized(using: "ButtonTitles"), for: UIControlState.normal)
Use Buttons instead ButtonTitles

http://joxi.ru/zANa6QesBqPWj2

**Comment by MikhailKupriyanov** [comment]
For label:
 lbl_name.text = "Name".localized()
You need use  lbl_name.text = "Name".localized(using: "File")
Or
Create Localizable.strings, add "Name" = "نا"; and use  lbl_name.text = "Name".localized()

**Comment by Nauman7222** [comment]
hi, @MikhailKupriyanov  

It works now, thanks for help.
