### ISSUE TITLE
Runtime localization not working

### ISSUE THREAD

**Issue by BhavinGupta** [marmelroy/Localize-Swift#94]
I am not able to change my localization at run time even after following your guidance.
language changes after running the app from killing state with new launch at that time my language gets changed.

i am not getting why it is not working even after adding observer to the view controller?

**Comment by MikhailKupriyanov** [comment]
show your code: 
1. When you change language
2. Observer and method where you handle notification

**Comment by BhavinGupta** [comment]
I have resolved this issue by my own there was some mistake in localizing the text with a small change of .localized() method in View Controller i am now able to change the language thank you.
